/**
 * This class will take wheels generated by RandomiseWheels and test if they have a win line or not
 * For time being win line will mean 2 or more of the same symbols in a row anywhere on a wheel
 * 
 *  (x,x,x,x,x) = biggest win
 *  (x,x,x,x,Y) OR (Y,x,x,x,x,)= 2nd biggest win
 * 	(x,x,x,Y,W) OR (Y,x,x,x,Y) OR (Y,W,x,x,x) = third biggest win
 *  (x,x,Y,W,Z) OR (Y,x,x,Y,Z) OR (Y,Z,x,x,Y) OR (Y,W,Z,x,x) = smallest win
 * 
 */


/**
 * @author mikey
 *
 */
public class CheckWheels {
	public  double TenModifier = 1.0;
	public  double JackModifier = 2.0;
	public  double QueenModifier = 4.0;
	public  double KingModifier = 20.0;
	public  double AceModifier = 50.0;	
	
	public  int TwoTenMatches = 0;
	public  int ThreeTenMatches = 0;
	public  int FourTenMatches = 0;
	public  int FiveTenMatches = 0;

	
	public  int TwoJackMatches = 0;
	public  int ThreeJackMatches = 0;
	public  int FourJackMatches = 0;
	public  int FiveJackMatches = 0;	
	
	
	public  int TwoQueenMatches = 0;
	public  int ThreeQueenMatches = 0;
	public  int FourQueenMatches = 0;
	public  int FiveQueenMatches = 0;

	public  int TwoKingMatches = 0;
	public  int ThreeKingMatches = 0;
	public  int FourKingMatches = 0;
	public  int FiveKingMatches = 0;

	public  int TwoAceMatches = 0;
	public  int ThreeAceMatches = 0;
	public  int FourAceMatches = 0;	
	public  int FiveAceMatches = 0;
	
	/**
	 * @param args
	 */
	public  void main(String[] args) {
		// TODO Auto-generated method

	}
	
	public  void incrementFields(int NumberOfMatches, double Modifier){
		if (Modifier == TenModifier){switch(NumberOfMatches){
			case 1: TwoTenMatches++;
			break;
			case 2: ThreeTenMatches++;
			break;
			case 3: FourTenMatches++;
			break;
			case 4: FiveTenMatches++;
			break;
		}} else if (Modifier == JackModifier){switch(NumberOfMatches){
			case 1: TwoJackMatches++;
			break;
			case 2: ThreeJackMatches++;
			break;
			case 3: FourJackMatches++;
			break;
			case 4: FiveJackMatches++;
			break;
		}} else if (Modifier == QueenModifier){switch(NumberOfMatches){
			case 1: TwoQueenMatches++;
			break;
			case 2: ThreeQueenMatches++;
			break;
			case 3: FourQueenMatches++;
			break;
			case 4: FiveQueenMatches++;
			break;
		}} else if (Modifier == KingModifier){switch(NumberOfMatches){
			case 1: TwoKingMatches++;
			break;
			case 2: ThreeKingMatches++;
			break;
			case 3: FourKingMatches++;
			break;
			case 4: FiveKingMatches++;
			break;
		}} else if (Modifier == AceModifier){switch(NumberOfMatches){
			case 1: TwoAceMatches++;
			break;
			case 2: ThreeAceMatches++;
			break;
			case 3: FourAceMatches++;
			break;
			case 4: FiveAceMatches++;
			break;
}}
		
	}
	
	public  double checkWheels(int[][] wheels, int NumberOfPayLines){	
		double value = 0;
		int NumberOfMatches = 0;
		double Modifier = 0;
		switch(NumberOfPayLines){
		case 1: 
			value = -1;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 2:
			value = -2;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 3:
			value = -3;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][3]);	
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 4:
			value = -4;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][3]);	
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][2],wheels[2][3],wheels[3][2],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 5:
			value = -5;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][3]);	
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][2],wheels[2][3],wheels[3][2],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][2],wheels[2][1],wheels[3][2],wheels[4][3]);	
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 6:
			value = -6;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][3]);	
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][2],wheels[2][3],wheels[3][2],wheels[4][1]);	
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);																//    /\
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][2],wheels[2][1],wheels[3][2],wheels[4][3]); // 	 /  \
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			//middle up one middle up one middle
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][1],wheels[2][2],wheels[3][3],wheels[4][2]);	// /\/\
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 7:
			value = -7;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	//1st row horizontal
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	//2nd row horizontal
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][3]);	//third row horizontal
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][2],wheels[2][3],wheels[3][2],wheels[4][1]);	//first row V shape
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);																
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][2],wheels[2][1],wheels[3][2],wheels[4][3]); //third row /\ shape
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			//middle up one middle up one middle
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][1],wheels[2][2],wheels[3][3],wheels[4][2]);	// 2nd row up zigzag
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][3],wheels[2][2],wheels[3][3],wheels[4][2]);	// 2nd row down zigzag
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 8:
			value = -8;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	//1st row horizontal
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	//2nd row horizontal
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][3]);	//third row horizontal
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][2],wheels[2][3],wheels[3][2],wheels[4][1]);	//first row V shape
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);																
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][2],wheels[2][1],wheels[3][2],wheels[4][3]); //third row /\ shape
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			//middle up one middle up one middle
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][1],wheels[2][2],wheels[3][3],wheels[4][2]);	// 2nd row up zigzag
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][3],wheels[2][2],wheels[3][3],wheels[4][2]);	// 2nd row down zigzag
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][2]);	// 2nd row trough \___/
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 9:
			value = -9;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	//1st row horizontal
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	//2nd row horizontal
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][3]);	//third row horizontal
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][2],wheels[2][3],wheels[3][2],wheels[4][1]);	//first row V shape
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);																
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][2],wheels[2][1],wheels[3][2],wheels[4][3]); //third row /\ shape
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			//middle up one middle up one middle
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][1],wheels[2][2],wheels[3][3],wheels[4][2]);	// 2nd row up zigzag
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][3],wheels[2][2],wheels[3][3],wheels[4][2]);	// 2nd row down zigzag
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][2]);	// 2nd row trough \___/
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);																	//					___
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][2]);	// 2nd row counter trough  /   \
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
		case 10:
			value = -10;
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][1]);	//1st row horizontal
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][2]);	//2nd row horizontal
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][3]);	//third row horizontal
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][2],wheels[2][3],wheels[3][2],wheels[4][1]);	//first row V shape
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);																
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][3],wheels[1][2],wheels[2][1],wheels[3][2],wheels[4][3]); //third row /\ shape
			Modifier = getModifier(wheels[0][3]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			//middle up one middle up one middle
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][1],wheels[2][2],wheels[3][3],wheels[4][2]);	// 2nd row up zigzag
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][3],wheels[2][2],wheels[3][3],wheels[4][2]);	// 2nd row down zigzag
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][3],wheels[2][3],wheels[3][3],wheels[4][2]);	// 2nd row trough \___/
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);																	//						___
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][2],wheels[1][1],wheels[2][1],wheels[3][1],wheels[4][2]);	// 2nd row counter trough  /   \
			Modifier = getModifier(wheels[0][2]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			NumberOfMatches = numberOfMatchesOnLine(wheels[0][1],wheels[1][2],wheels[2][2],wheels[3][2],wheels[4][3]);	// 1st row sideways lightning bolt
			Modifier = getModifier(wheels[0][1]);
			incrementFields(NumberOfMatches, Modifier);
			value = value + (NumberOfMatches * Modifier);
			break;
			
		}		
		
		//checks for symbol matching quantities
		
		return value;
	}
	
	public  int numberOfMatchesOnLine(int i,int j, int k, int l, int m){
		if(i == j){
			if(j == k){
				if(k == l){
					if(l == m){
						return 4;
					}
					return 3;
				}
				return 2;
			}			
			return 1;
		}
		else{
			return 0;
		}
	}

	public  double getModifier(int num){
		double modifier = 0;
		switch(num){
		case 0 :
			modifier = TenModifier;
			break;
		case 1 :
			modifier = JackModifier;
			break;
		case 2 :
			modifier = QueenModifier;
			break;
		case 3 :
			modifier = KingModifier;
			break;
		case 4 :
			modifier = AceModifier;
			break;		
		}		
		return modifier;
	}

	public  int getTwoTenMatches() {
		return TwoTenMatches;
	}

	public  int getThreeTenMatches() {
		return ThreeTenMatches;
	}

	public  int getFourTenMatches() {
		return FourTenMatches;
	}

	public  int getFiveTenMatches() {
		return FiveTenMatches;
	}

	public  int getTwoJackMatches() {
		return TwoJackMatches;
	}

	public  int getThreeJackMatches() {
		return ThreeJackMatches;
	}

	public  int getFourJackMatches() {
		return FourJackMatches;
	}

	public  int getFiveJackMatches() {
		return FiveJackMatches;
	}

	public  int getTwoQueenMatches() {
		return TwoQueenMatches;
	}

	public  int getThreeQueenMatches() {
		return ThreeQueenMatches;
	}

	public  int getFourQueenMatches() {
		return FourQueenMatches;
	}

	public  int getFiveQueenMatches() {
		return FiveQueenMatches;
	}

	public  int getTwoKingMatches() {
		return TwoKingMatches;
	}

	public  int getThreeKingMatches() {
		return ThreeKingMatches;
	}

	public  int getFourKingMatches() {
		return FourKingMatches;
	}

	public  int getFiveKingMatches() {
		return FiveKingMatches;
	}

	public  int getTwoAceMatches() {
		return TwoAceMatches;
	}

	public  int getThreeAceMatches() {
		return ThreeAceMatches;
	}

	public  int getFourAceMatches() {
		return FourAceMatches;
	}

	public  int getFiveAceMatches() {
		return FiveAceMatches;
	}
	public  double getTenModifier() {
		return TenModifier;
	}

	public  double getJackModifier() {
		return JackModifier;
	}

	public  double getQueenModifier() {
		return QueenModifier;
	}

	public  double getKingModifier() {
		return KingModifier;
	}

	public  double getAceModifier() {
		return AceModifier;
	}
	
}
